In [1]:
#Importing pandas library and giving it an alias as pd.Pandas library is mainly used for database table structured data.
import pandas as pd

In [2]:
#We are now assigning all the datas of Salary_Data.csv file to a variable called dataset using read_csv function which is under padas library.
dataset=pd.read_csv("Salary_Data.csv")

In [3]:
#Checking the value of dataset variable.
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
#We are saving YearsExperience column datas into independent variable & Salary column datas into dependent variable
independent=dataset[["YearsExperience"]]
dependent=dataset[["Salary"]]

In [9]:
#Checking the value of independent variable.
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [10]:
#Checking the value of dependent variable.
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [12]:
#Importing train_test_split function from sklearn library.Importing only the required function without importing all the sk learn library.
from sklearn.model_selection import train_test_split
#Calling train_test_split function with independent and dependent variable and Output gives you 4 array values.2 for training set and 2 for test set.
#Assiging the 4 array output as X_train,X_test,Y_train,Y_test
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [13]:
#Importing LinearRegression function from sklearn library
from sklearn.linear_model import LinearRegression
#Assiging the LinearRegression function to a variable called regressor.Since the LinearRegression function is assigned to variable called regressor 
#LinearRegression function behaves as a class.
regressor=LinearRegression()
#We are now calling fit function through regressor variable passing the training dataset so that the model gets created.
#The model is gets created using the fit function means the W=weight & b=bias gets calculated.
regressor.fit(X_train,y_train)

LinearRegression()

In [14]:
#regressor.coef_ is the place where calculated weight is stored for this dataset which is assiged to a variable weight
weight=regressor.coef_

In [15]:
#printing the weight variable value
weight

array([[9360.26128619]])

In [16]:
#regressor.intercept_ is the place where calculated bias is stored for this dataset which is assiged to a variable bias
bias=regressor.intercept_

In [17]:
#printing the bias variable value
bias

array([26777.3913412])

In [18]:
#We are now predicting the output using the input test data.
y_pred=regressor.predict(X_test)

In [19]:
#Importing the r2_score function from sklearn library for evaluation.
from sklearn.metrics import r2_score 
#Calculating the r2_score with predicted data and actual test data.
r_score=r2_score(y_pred,y_test)

In [20]:
#Checking the r_score value and if it is near to 1 it is a good model.
r_score

0.9710122289422968

In [21]:
#Importing pickle library which is used to save model in python.
import pickle
#creating a file with pickle extension .sav
filename="finalized_model_linear.sav"
#Wrting the model into the file. 'wb' represents write byte.
pickle.dump(regressor,open(filename,'wb'))